using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace Xing.Entities
{
    public enum UserFields
    {
        [Description("id")]
        ID,
        [Description("first_name")]
        FirstName,
        [Description("last_name")]
        LastName,
        [Description("display_name")]
        DisplayName,
        [Description("page_name")]
        PageName,
        [Description("permalink")]
        Permalink,
        [Description("gender")]
        Gender,
        [Description("birth_date")]
        BirthDate,
        [Description("birth_date.day")]
        BirthDate_Day,
        [Description("birth_date.month")]
        BirthDate_Month,
        [Description("birth_date.year")]
        BirthDate_Year,
        [Description("active_email")]
        ActiveEmail,
        [Description("time_zone")]
        TimeZone,
        [Description("time_zone.name")]
        TimeZone_Name,
        [Description("time_zone.utc_offset")]
        TimeZone_UtcOffset,
        [Description("premium_services")]
        PremiumServices,
        [Description("badges")]
        Badges,
        [Description("wants")]
        Wants,
        [Description("haves")]
        Haves,
        [Description("interests")]
        Interests,
        [Description("organisation_member")]
        OrganisationMember,
        [Description("languages")]
        Languages,
        [Description("private_address")]
        PrivateAddress,
        [Description("private_address.city")]
        PrivateAddress_City,
        [Description("private_address.country")]
        PrivateAddress_Country,
        [Description("private_address.zip_code")]
        PrivateAddress_ZipCode,
        [Description("private_address.street")]
        PrivateAddress_Street,
        [Description("private_address.phone")]
        PrivateAddress_Phone,
        [Description("private_address.fax")]
        PrivateAddress_Fax,
        [Description("private_address.province")]
        PrivateAddress_Province,
        [Description("private_address.email")]
        PrivateAddress_Email,
        [Description("private_address.mobile_phone")]
        PrivateAddress_MobilePhone,
        [Description("business_address")]
        BusinessAddress,
        [Description("business_address.city")]
        BusinessAddress_City,
        [Description("business_address.country")]
        BusinessAddress_Country,
        [Description("business_address.zip_code")]
        BusinessAddress_ZipCode,
        [Description("business_address.street")]
        BusinessAddress_Street,
        [Description("business_address.phone")]
        BusinessAddress_Phone,
        [Description("business_address.fax")]
        BusinessAddress_Fax,
        [Description("business_address.province")]
        BusinessAddress_Province,
        [Description("business_address.email")]
        BusinessAddress_Email,
        [Description("business_address.mobile_phone")]
        BusinessAddress_MobilePhone,
        [Description("web_profiles")]
        WebProfiles,
        [Description("web_profiles.qype")]
        WebProfiles_Qype,
        [Description("web_profiles.google_plus")]
        WebProfiles_GooglePlus,
        [Description("web_profiles.blog")]
        WebProfiles_Blog,
        [Description("web_profiles.homepage")]
        WebProfiles_Homepage,
        [Description("instant_messaging_accounts")]
        InstantMessagingAccounts,
        [Description("instant_messaging_accounts.skype")]
        InstantMessagingAccounts_Skype,
        [Description("instant_messaging_accounts.googletalk")]
        InstantMessagingAccounts_GoogleTalk,
        [Description("professional_experience")]
        ProfessionalExperience,
        [Description("professional_experience.primary_company")]
        ProfessionalExperience_PrimaryCompany,
        [Description("professional_experience.primary_company.name")]
        ProfessionalExperience_PrimaryCompany_Name,
        [Description("professional_experience.primary_company.title")]
        ProfessionalExperience_PrimaryCompany_Title,
        [Description("professional_experience.primary_company.company_size")]
        ProfessionalExperience_PrimaryCompany_CompanySize,
        [Description("professional_experience.primary_company.tag")]
        ProfessionalExperience_PrimaryCompany_Tag,
        [Description("professional_experience.primary_company.url")]
        ProfessionalExperience_PrimaryCompany_Url,
        [Description("professional_experience.primary_company.career_level")]
        ProfessionalExperience_PrimaryCompany_CareerLevel,
        [Description("professional_experience.primary_company.begin_date")]
        ProfessionalExperience_PrimaryCompany_BeginDate,
        [Description("professional_experience.primary_company.description")]
        ProfessionalExperience_PrimaryCompany_Description,
        [Description("professional_experience.primary_company.end_date")]
        ProfessionalExperience_PrimaryCompany_EndDate,
        [Description("professional_experience.primary_company.industry")]
        ProfessionalExperience_PrimaryCompany_Industry,
        [Description("professional_experience.non_primary_companies")]
        ProfessionalExperience_NonPrimaryCompanies,
        [Description("professional_experience.non_primary_companies.name")]
        ProfessionalExperience_NonPrimaryCompanies_Name,
        [Description("professional_experience.non_primary_companies.title")]
        ProfessionalExperience_NonPrimaryCompanies_Title,
        [Description("professional_experience.non_primary_companies.company_size")]
        ProfessionalExperience_NonPrimaryCompanies_CompanySize,
        [Description("professional_experience.non_primary_companies.tag")]
        ProfessionalExperience_NonPrimaryCompanies_Tag,
        [Description("professional_experience.non_primary_companies.url")]
        ProfessionalExperience_NonPrimaryCompanies_Url,
        [Description("professional_experience.non_primary_companies.career_level")]
        ProfessionalExperience_NonPrimaryCompanies_CareerLevel,
        [Description("professional_experience.non_primary_companies.begin_date")]
        ProfessionalExperience_NonPrimaryCompanies_BeginDate,
        [Description("professional_experience.non_primary_companies.description")]
        ProfessionalExperience_NonPrimaryCompanies_Description,
        [Description("professional_experience.non_primary_companies.end_date")]
        ProfessionalExperience_NonPrimaryCompanies_EndDate,
        [Description("professional_experience.non_primary_companies.industry")]
        ProfessionalExperience_NonPrimaryCompanies_Industry,
        [Description("professional_experience.awards")]
        ProfessionalExperience_Awards,
        [Description("professional_experience.awards.name")]
        ProfessionalExperience_Awards_Name,
        [Description("professional_experience.awards.date_awarded")]
        ProfessionalExperience_Awards_DateAwarded,
        [Description("professional_experience.awards.url")]
        ProfessionalExperience_Awards_Url,
        [Description("educational_background")]
        EducationalBackground,
        [Description("educational_background.schools")]
        EducationalBackground_Schools,
        [Description("educational_background.schools.name")]
        EducationalBackground_Schools_Name,
        [Description("educational_background.schools.degree")]
        EducationalBackground_Schools_Degree,
        [Description("educational_background.schools.notes")]
        EducationalBackground_Schools_Notes,
        [Description("educational_background.schools.subject")]
        EducationalBackground_Schools_Subject,
        [Description("educational_background.schools.begin_date")]
        EducationalBackground_Schools_BeginDate,
        [Description("educational_background.schools.end_date")]
        EducationalBackground_Schools_EndDate,
        [Description("qualifications")]
        Qualifications,
        [Description("photo_urls")]
        PhotoUrls,
        [Description("photo_urls.large")]
        PhotoUrls_Large,
        [Description("photo_urls.mini_thumb")]
        PhotoUrls_MiniThumb,
        [Description("photo_urls.thumb")]
        PhotoUrls_Thumb,
        [Description("photo_urls.medium_thumb")]
        PhotoUrls_MediumThumb,
        [Description("photo_urls.maxi_thumb")]
        PhotoUrls_MaxiThumb,
    }

    public static class UserFieldsExtensions
    {
        public static string ToDescriptionString(this UserFields val)
        {
            DescriptionAttribute[] attributes = (DescriptionAttribute[])val.GetType().GetField(val.ToString()).GetCustomAttributes(typeof(DescriptionAttribute), false);
            return attributes.Length > 0 ? attributes[0].Description : string.Empty;
        }
    }
}
